Repository SKA-INAF/scutout, pull requests merged in 2020-05, with the labels that each got.

#2 Add utils unit tests; minor bug fixes
  .gitignore
  scutout/utils.py
  tests/__init__.py
  tests/context.py
  tests/test_utils.py
Labels: enhancement

#3 update README
  README.md
Labels: documentation

#4 Fixes unintended brightness scale inversion in MIPS and MSX surveys
  scutout/utils.py
  tests/test_utils.py
Labels: bug

#5 Fixes brigthness conversion factor for MIPS and MSX surveys
  scutout/utils.py
  tests/test_utils.py
Labels: bug

#6 Removes non-significant trailing spaces in BUNIT header
  scutout/utils.py
Labels: bug

#9 Minor fixes on header treatment and beam corrections
  scutout/cutout_extractor.py
  scutout/utils.py
  tests/test_utils.py
Labels: bug
